	<%@ include file="top.phtml" %>
        <title><%syspref var="site.name" %> :: <%$title %></title>
        <%$heads %>
        <%@ include file="header.phtml" %>
	<%@ include file="pagebegin.phtml" %>

<!-- we need to provide a header for wiki content. -->
<% breadcrumbs var="$object.path" %>
<%@ include file="space/trackback.phtml" %>
      <% if data["request"]["misc"]["object_is_weblog"] %>
      <% else %>
   <h3><%$title %></h3>
     <% endif %>
<small><img src="<%theme show="path"%>images/timeicon.gif" alt="" />
<%$object.nice_created %> by <img src="<%theme show="path"%>images/author.gif" alt="" />
<%$object.author.name%>
</small><p/>
<div class="flash-message"><% flash %></div>

<% if data["user_object"] && ! data["request"]["misc"]["object_is_weblog"] %>
  <%$content%>
<p>
<% else %>
  <%$content%>
<% endif %>

<p>
      
<% if data["request"]["misc"]["object_is_weblog"] %>
<% elseif sizeof(data->object["attachments"])%>
<h3>Attachments</h3>
<%@ include file="space/_displayattachments.phtml"%>
<p/>
<%endif %>
<!--
<i>Created by <%$author_username %>. Last updated by <%$editor_username %>,
<%friendly_date var="$object_version.created" %>. Version #<%$object_version.version%>.
</i>      
-->
<small>
<% if data["request"]["misc"]["object_is_weblog"] %>
<%else %>
<% if sizeof(data->object["categories"]) %> Posted in <% implode var="$object.category_links" nice="and"%> 
<strong>|</strong> <%endif %>
         <% if data["numcomments"] %>
                 <a href="#" onclick="displayComments('wiper', '<%$obj%>')"><%$numcomments %> comments</a>
            <% else %>
                 No comments
            <% endif %>
 <strong>|</strong> <a id="PostComment" href="/exec/comments/<%$obj%>">Post
a Comment</a> <strong>|</strong> <a href="/rss/<%$obj%>?type=comments">RSS Feed</a>
  <% if data["metadata"]["trackbacks"] %> <strong>|</strong> <a href="/exec/display_trackbacks/<%$obj%>" 
id="TrackBacks"><%sizeof var="$metadata.trackbacks"%> TrackBacks</a> <% endif %>
  <% if data["metadata"]["pingbacks"] %> <strong>|</strong> <a href="/exec/display_pingbacks/<%$obj%>" 
id="PingBacks"><%sizeof var="$metadata.pingbacks"%> PingBacks</a> <% endif %>
<strong>|</strong> <a id="BackLinks" 
href="/exec/backlinks/<%$obj%>">BackLinks</a> |
</small>
         <p/>

<div id="wiper" style="display:none;"></div>
<% endif %>
<! -- bottom of pagebegin.phtml -->
<%@include file="footer.phtml" %>
<%@include file="bottom.phtml" %>

