	<%@ include file="top.phtml" %>
        <title><%syspref var="site.name" %> :: <%$title %></title>
        <%$heads %>
        <%@ include file="header.phtml" %>
	<%@ include file="fpagebegin.phtml" %>

<!-- we need to provide a header for wiki content. -->
<% breadcrumbs var="$object.path" %>
<%@ include file="space/trackback.phtml" %>
      <% if data["request"]["misc"]["object_is_weblog"] %>
      <% else %>
   <h3><%$title %></h3>
<p>
     <% endif %>
<div class="flash-message"><% flash %></div>
<% if data["user_object"] && ! data["request"]["misc"]["object_is_weblog"] %>
  <%$content%>
<p>
<% else %>
  <%$content%>
<% endif %>

<p>
      
<% if sizeof(data->object["attachments"])%>
<h3>Attachments</h3>
<%@ include file="space/_displayattachments.phtml"%>
<p/>
<%endif %>
<p>

<%@include file="pageend.phtml" %>
<%@include file="footer.phtml" %>
<%@include file="bottom.phtml" %>

