
 <div class="post" id="post-<%$entry.id%>">
                        <h2><a href="/space/<%$entry.path%>" rel="bookmark" title="Permanent Link to <%$subject%>">
                                 <%$subject%></a></h2>
<p class="info"><small><img src="<%theme show="path"%>/images/timeicon.gif" alt="" />
<%$entry.nice_created %> by <img src="<%theme show="path"%>/images/author.gif" alt="" />
<%$entry.author.Name%> </small></p>

                        <div class="entry">
                             <%render content="$content" object="$entry"%>
                        </div>

                        <p class="info"><% if 
sizeof(data->entry["categories"]) %> Posted in <% implode var="$entry.category_links" nice="and"%> <strong>|</strong> <%endif %> 
<a class="DisplayComments" id="<%$entry.id%>" onclick="displayComments('wiper<%$entry.id%>', '<%$entry.path%>'); 
return false;"><%sizeof var="$entry.comments"%> comments</a>
<strong>|</strong>
<a href="/exec/comments/<%$entry.path%>">Post a Comment</a> 
<strong>|</strong>
</div>
<div id="wiper<%$entry.id%>" style="display:none; padding-left:20px;"></div>
