	</head>
<body class="tundra">
   <!-- Begin Wrapper -->
   <div id="l1wrapper">

         <!-- Begin Header -->
         <div id="l1header">
		<%action_link controller="/space"%>
                       <h1><%syspref var="site.name" %></h1>
                                <h2><%syspref var="site.tagline" %></h2>
		</a>

	</div>
                 <!-- End Header -->

<%@include file="tagline.phtml"%>

        <div id="main">
                 <!-- Begin Left Column -->
                 <div id="leftcolumn">

<!--
Language:  <%language_selector%>
-->
 <% snip snip="themes/default/portlet-1" %>

                <p>
                        &nbsp;
                <p>

<% if data["user_object"] %>
<a href="/admin">admin</a>
<p>
<a href="/exec/logout">logout</a>
<% else %>
<a href="/exec/login" id="Login">login</a>
<% endif %>



                 </div>
                 <!-- End Left Column -->

                 <!-- Begin Right Column -->
                 <div id="l1rightcolumn">






