</head>
<body>
<div id="actions" class="menu"><div id="closebutton" class="closebutton"><a onclick="menuLayers.hide()">Close</a></div>
<div id="actions_contents" class="action_contents"></div>
</div>

<div class="wrap clearfix">
  <div class="header"><strong><%syspref var="site.name" %></strong><br/><em><%syspref var="site.tagline" %></em></div>
  <div class="topnav" id="nav">
    <ul>
      <%@include file="tagline.phtml" %>
    </ul>
  </div>

<div class="container clearfix">
<!--
Language:  <%language_selector%>
-->
<xdiv class="page_body">

