<!-- this is adminfooter.phtml -->
                 </div>
                 <!--   End Right Column -->
                </div>
                 <!-- Begin Footer -->
                 <div id="footer">

<%syspref var="site.copyright" %>

             </div>
                 <!-- End Footer -->

   </div>
   <!-- End Wrapper -->

<%if data->config->config_name == "dev" %>
<script src="<%syspref var="site.url"%>static/javascripts/dojo/dojo.js" type="text/javascript"></script>
<% else %>
<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.6.1/dojo/dojo.xd.js" type="text/javascript"></script>
<% endif %>

<script type='text/javascript'>
<%if data->config->config_name == "dev" %>
dojo.registerModulePath("fins", "<%syspref var="site.url"%>static/javascripts/fins");	
<% else %>
dojo.registerModulePath("fins", "<%syspref var="site.url"%>static/javascripts/fins_release");	
<% endif %>
</script>
<script src="<%syspref var="site.url"%>static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="<%syspref var="site.url"%>static/javascripts/bootstrap.js" type="text/javascript"></script>
<script type="text/javascript">
<% list_retrieve var="$jsfooter" %>
</script>
</body>
</html>


