                 </div>
                 <!--   End Right Column -->
                </div>
                 <!-- Begin Footer -->
                 <div id="footer">

<%syspref var="site.copyright" %>

             </div>
                 <!-- End Footer -->

   </div>
   <!-- End Wrapper -->

<%if data->config->config_name == "dev" %>
        <script src="<%syspref var="site.url"%>static/javascripts/dojo/dojo.js" type="text/javascript"></script>
<% else %>
	<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.6.1/dojo/dojo.xd.js" type="text/javascript"></script>
<% endif %>
<script type='text/javascript'>
<%if data->config->config_name == "dev" %>
dojo.registerModulePath("fins", "<%syspref var="site.url"%>static/javascripts/fins");
<% else %>
dojo.registerModulePath("fins", "<%syspref var="site.url"%>static/javascripts/fins_release");
<% endif %>
</script>
<script src="<%syspref var="site.url"%>static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="<%syspref var="site.url"%>static/javascripts/bootstrap.js" type="text/javascript"></script>
<script type="text/javascript" src="http://api.recaptcha.net/js/recaptcha_ajax.js"></script>
<script type='text/javascript'>

        dojo.require("dojo.store.JsonRest");
        dojo.require("dijit.Dialog");
        dojo.require("fins.widget.Recaptcha");
        dojo.require("fins.widget.Comments");
        dojo.require("dijit.form.DateTextBox");
        dojo.require("dijit.TooltipDialog");
        dojo.require("dojox.form.Uploader");
        dojo.require("dojox.form.uploader.FileList");
        dojo.require("dijit.Menu");
        dojo.require("dijit.MenuItem");
        dojo.require("dijit.Tree");
//      dojo.require("dojox.form.uploader.plugins.IFrame");
        dojo.require("dojox.form.uploader.plugins.Flash");
    dojo.ready(function(){
//        alert("Dojo version " + dojo.version + " is loaded");
    });
// insert content inserted previously in the parse process
  <% list_retrieve var="$jsfooter" %>
</script>

