</xdiv>
 <div class="footer" id="footer"> 
<a href="<%syspref var="site.url"%>">home</a>&nbsp;&nbsp;:&nbsp;&nbsp; 
<a href="/space/contact%20info">contact info</a>
</br>
<center>
<%syspref var="site.copyright" %>
</p></center>
</div>

<script src="http://download.dojotoolkit.org/dojo_0.4.2.js"></script>
<script type='text/javascript'>
dojo.addOnLoad(function(){
  dojo.registerModulePath("fins", "http://hww3.riverweb.com/static/javascripts/fins");
  dojo.require("dojo.widget.*");
  dojo.require("fins.widget.ComboPicker");
  }
);
</script>
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="/static/javascripts/rounded-corners.js" type="text/javascript"></script>
<script src="/static/javascripts/bootstrap.js" type="text/javascript"></script>

<script type='text/javascript'>
  <% list_retrieve var="$jsfooter" %>
  make_corners();
</script>
