<!-- this is header.phtml -->
   <link rel="STYLESHEET" type="text/css" href="/theme/default/default.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>style.css"/>
   <!-- IE doesn't like XHTML markup for an empty script container :/ -->

<script type='text/javascript'>
  djConfig = {
    isDebug : false,
    disableFlashStorage : true
  };

</script>
<div style="display:none" id="object"><%$obj%></div>
