<!-- this is header.phtml -->
    <% if data["object_is_weblog"] %>
      <link rel="alternate" type="application/atom+xml" title="Atom Weblog Feed" href="/atom/<%$obj%>" />
      <link rel="alternate" type="application/rss+xml" title="RSS Weblog Feed" href="/rss/<%$obj%>" />
    <% elseif data["obj"] %>
      <link rel="alternate" type="application/atom+xml" title="Atom Comments Feed" href="/atom/<%$obj%>?type=comments" />
      <link rel="alternate" type="application/rss+xml" title="RSS Comments Feed" href="/rss/<%$obj%>?type=comments" />
    <% endif %>

   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>default.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>style.css"/>
   <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/dojo/1.6/dijit/themes/tundra/tundra.css"/>
   <link rel="STYLESHEET" type="text/css" href="<%syspref var="site.url"%>/static/javascripts/fins/widget/templates/Comments.css"/>
   <!-- IE doesn't like XHTML markup for an empty script container :/ -->

<script type='text/javascript'>
  djConfig = {
    parseOnLoad: true,
    debugAtAllCosts:false,
    disableFlashStorage : true,
<% if data->config->config_name == "dev" %>
    useXDomain: false,
    isDebug:true,
<% else %>
    useXDomain: true,
    isDebug: false,
<% endif %>
  };

</script>

<div style="display:none" id="object"><%$obj%></div>

