<li> <a href="/space/start">start</a> </li>
<li> <a href="/space/object-index">index</a> </li>
<% if data["user_object"] %>
<li> <a href="/exec/logout">logout</a> </li>
<% if data["object_is_weblog"] %>
<li> <a href="/exec/post/<%$obj%>" id="PostBlog">post blog</a> 
</li>
<% endif %>
<% if data["is_admin"]==1 %>
<li> <a href="/admin/">admin</a> </li>
   <% endif %>
   <% else %>
<li> <a href="/exec/login" id="Login">login</a> </li>
<% endif %>

<% if data["user_object"]  %>
<li> <a href="/exec/actions/<%$obj%>" id="Actions">actions</a> </li>
<% endif %>
