                 <!-- Begin Navigation -->
         <div id="navigation">
                <ul id="mainNav">
                        <li id="mainNavOn">
                                <%action_link controller="/space" args="about"%>About</a>
                        </li>
                        <li id="mainNavOff">
                                <a href="">Support Forums</a>
                        </li>
                        <li id="mainNavOff">
                                <a href="">Module Market</a>
                        </li>
                        <li id="mainNavOff">
                                <a href="">Documentation</a>
                        </li>
                        <li id="mainNavOff">
                                <a href="">Get Involved</a>
                        </li>
                </ul>

                 </div>
                 <!-- End Navigation -->
